// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PeerTopicInfo struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Topics               []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerTopicInfo) Reset()         { *m = PeerTopicInfo{} }
func (m *PeerTopicInfo) String() string { return proto.CompactTextString(m) }
func (*PeerTopicInfo) ProtoMessage()    {}
func (*PeerTopicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *PeerTopicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerTopicInfo.Unmarshal(m, b)
}
func (m *PeerTopicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerTopicInfo.Marshal(b, m, deterministic)
}
func (m *PeerTopicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerTopicInfo.Merge(m, src)
}
func (m *PeerTopicInfo) XXX_Size() int {
	return xxx_messageInfo_PeerTopicInfo.Size(m)
}
func (m *PeerTopicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerTopicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerTopicInfo proto.InternalMessageInfo

func (m *PeerTopicInfo) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *PeerTopicInfo) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type PublishData struct {
	Info                 *PeerTopicInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Data                 *Data          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PublishData) Reset()         { *m = PublishData{} }
func (m *PublishData) String() string { return proto.CompactTextString(m) }
func (*PublishData) ProtoMessage()    {}
func (*PublishData) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *PublishData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishData.Unmarshal(m, b)
}
func (m *PublishData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishData.Marshal(b, m, deterministic)
}
func (m *PublishData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishData.Merge(m, src)
}
func (m *PublishData) XXX_Size() int {
	return xxx_messageInfo_PublishData.Size(m)
}
func (m *PublishData) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishData.DiscardUnknown(m)
}

var xxx_messageInfo_PublishData proto.InternalMessageInfo

func (m *PublishData) GetInfo() *PeerTopicInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PublishData) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Data struct {
	Topic                []string `protobuf:"bytes,1,rep,name=topic,proto3" json:"topic,omitempty"`
	Raw                  []byte   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetTopic() []string {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Data) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerTopicInfo)(nil), "rpc.PeerTopicInfo")
	proto.RegisterType((*PublishData)(nil), "rpc.PublishData")
	proto.RegisterType((*Response)(nil), "rpc.Response")
	proto.RegisterType((*Data)(nil), "rpc.Data")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x26, 0xb6, 0x66, 0x62, 0xa1, 0x8e, 0x22, 0x41, 0x10, 0xca, 0x22, 0xd2, 0x83,
	0x04, 0x89, 0x17, 0xd1, 0xab, 0x17, 0x0f, 0x42, 0x59, 0xdb, 0x07, 0xd8, 0xc4, 0x69, 0x1b, 0xd0,
	0xec, 0xb2, 0x9b, 0xe2, 0x5b, 0xf8, 0xcc, 0xb2, 0xd3, 0x84, 0xa2, 0x16, 0x0f, 0xde, 0x66, 0x66,
	0xff, 0xf9, 0xff, 0x8f, 0x61, 0x21, 0xb6, 0xa6, 0xcc, 0x8c, 0xd5, 0x8d, 0xc6, 0xd0, 0x9a, 0x52,
	0x3c, 0xc0, 0x68, 0x46, 0x64, 0xe7, 0xda, 0x54, 0xe5, 0x53, 0xbd, 0xd4, 0x88, 0x10, 0x19, 0x22,
	0x9b, 0x06, 0x93, 0x60, 0x1a, 0x4b, 0xae, 0xf1, 0x0c, 0x06, 0x8d, 0x17, 0xb8, 0xb4, 0x3f, 0x09,
	0xa7, 0xb1, 0x6c, 0x3b, 0x31, 0x87, 0x64, 0xb6, 0x29, 0xde, 0x2a, 0xb7, 0x7e, 0x54, 0x8d, 0xc2,
	0x2b, 0x88, 0xaa, 0x7a, 0xa9, 0x79, 0x35, 0xc9, 0x31, 0xf3, 0x51, 0xdf, 0xcc, 0x25, 0xbf, 0xe3,
	0x05, 0x44, 0xaf, 0xaa, 0x51, 0x69, 0x9f, 0x75, 0x31, 0xeb, 0xbc, 0x81, 0xe4, 0xb1, 0xb8, 0x84,
	0x43, 0x49, 0xce, 0xe8, 0xda, 0x11, 0xa6, 0x30, 0x7c, 0x27, 0xe7, 0xd4, 0x8a, 0x5a, 0xa0, 0xae,
	0x15, 0x19, 0x44, 0x1c, 0x7a, 0x0a, 0x07, 0x4c, 0x93, 0x06, 0x8c, 0xb6, 0x6d, 0x70, 0x0c, 0xa1,
	0x55, 0x1f, 0x9c, 0x70, 0x24, 0x7d, 0x99, 0x7f, 0xf6, 0x21, 0x7a, 0x26, 0xb7, 0xc6, 0x3b, 0x38,
	0x96, 0xb4, 0xaa, 0x5c, 0xe3, 0xc1, 0x5a, 0x7c, 0xdc, 0x03, 0x7b, 0x3e, 0xe2, 0x59, 0x87, 0x22,
	0x7a, 0x78, 0x0f, 0x27, 0x8b, 0xda, 0xfe, 0x6f, 0xf7, 0x1a, 0x86, 0x9d, 0x7e, 0xbc, 0xd5, 0xef,
	0x0e, 0xf7, 0x5b, 0x9d, 0x41, 0xfc, 0xb2, 0x29, 0x5c, 0x69, 0xab, 0x82, 0xf6, 0xfa, 0xef, 0x8e,
	0x26, 0x7a, 0x37, 0x01, 0xe6, 0x90, 0x2c, 0x6a, 0xf7, 0xe7, 0xc6, 0xcf, 0x8c, 0x62, 0xc0, 0xbf,
	0xe0, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x14, 0xab, 0x9d, 0x12, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MeshClient is the client API for Mesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeshClient interface {
	RegisterToPublish(ctx context.Context, in *PeerTopicInfo, opts ...grpc.CallOption) (*Response, error)
	UnregisterToPublish(ctx context.Context, in *PeerTopicInfo, opts ...grpc.CallOption) (*Response, error)
	Publish(ctx context.Context, in *PublishData, opts ...grpc.CallOption) (*Response, error)
	Subscribe(ctx context.Context, in *PeerTopicInfo, opts ...grpc.CallOption) (Mesh_SubscribeClient, error)
	Unsubscribe(ctx context.Context, in *PeerTopicInfo, opts ...grpc.CallOption) (*Response, error)
}

type meshClient struct {
	cc *grpc.ClientConn
}

func NewMeshClient(cc *grpc.ClientConn) MeshClient {
	return &meshClient{cc}
}

func (c *meshClient) RegisterToPublish(ctx context.Context, in *PeerTopicInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.Mesh/RegisterToPublish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) UnregisterToPublish(ctx context.Context, in *PeerTopicInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.Mesh/UnregisterToPublish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) Publish(ctx context.Context, in *PublishData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.Mesh/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) Subscribe(ctx context.Context, in *PeerTopicInfo, opts ...grpc.CallOption) (Mesh_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Mesh_serviceDesc.Streams[0], "/rpc.Mesh/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &meshSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Mesh_SubscribeClient interface {
	Recv() (*Data, error)
	grpc.ClientStream
}

type meshSubscribeClient struct {
	grpc.ClientStream
}

func (x *meshSubscribeClient) Recv() (*Data, error) {
	m := new(Data)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *meshClient) Unsubscribe(ctx context.Context, in *PeerTopicInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.Mesh/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshServer is the server API for Mesh service.
type MeshServer interface {
	RegisterToPublish(context.Context, *PeerTopicInfo) (*Response, error)
	UnregisterToPublish(context.Context, *PeerTopicInfo) (*Response, error)
	Publish(context.Context, *PublishData) (*Response, error)
	Subscribe(*PeerTopicInfo, Mesh_SubscribeServer) error
	Unsubscribe(context.Context, *PeerTopicInfo) (*Response, error)
}

func RegisterMeshServer(s *grpc.Server, srv MeshServer) {
	s.RegisterService(&_Mesh_serviceDesc, srv)
}

func _Mesh_RegisterToPublish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerTopicInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).RegisterToPublish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Mesh/RegisterToPublish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).RegisterToPublish(ctx, req.(*PeerTopicInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_UnregisterToPublish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerTopicInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).UnregisterToPublish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Mesh/UnregisterToPublish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).UnregisterToPublish(ctx, req.(*PeerTopicInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Mesh/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).Publish(ctx, req.(*PublishData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PeerTopicInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServer).Subscribe(m, &meshSubscribeServer{stream})
}

type Mesh_SubscribeServer interface {
	Send(*Data) error
	grpc.ServerStream
}

type meshSubscribeServer struct {
	grpc.ServerStream
}

func (x *meshSubscribeServer) Send(m *Data) error {
	return x.ServerStream.SendMsg(m)
}

func _Mesh_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerTopicInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Mesh/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).Unsubscribe(ctx, req.(*PeerTopicInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mesh_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Mesh",
	HandlerType: (*MeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterToPublish",
			Handler:    _Mesh_RegisterToPublish_Handler,
		},
		{
			MethodName: "UnregisterToPublish",
			Handler:    _Mesh_UnregisterToPublish_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _Mesh_Publish_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _Mesh_Unsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Mesh_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc.proto",
}
